### ISSUE TITLE
Question about ViewerConfiguration Template

### ISSUE THREAD

**Issue by mmestrov** [Esri/image-discovery-app-js#41]
Richard,  this is a great app. I noticed that you have in the templates folder a viewerConfiguration.json.  Can you send me documentation on how to set this up. I don't need the imageQuery portion of this app. I really need to use the query layer and timeslider functionality using my rest endpoints.

Thanks

Michelle

**Comment by ACueva** [comment]
@mmestrov We're working on getting this fully documented.  We should have more info for you shortly.

**Comment by NatalieCampos** [comment]
@mmestrov The template has been fully documented on the ArcGIS Solutions website below.  If you have any more question please let us know.

http://solutions.arcgis.com/intelligence/templates/image-discovery/
