### ISSUE TITLE
Wondeful App. Can it accomodate Map Service Discovery?

### ISSUE THREAD

**Issue by codezas** [Esri/image-discovery-app-js#46]
Hi.

I just download and tried the app. It looks exceptional.

I was wondering if this app can support map discovery also. I have a tile map service with tiff images and I would like to show them same as images from image service.

Your help in this case would be appreciated.

**Comment by Rrivera5127** [comment]
I had a prototype for Vector Discovery (Map Services). Is this what you are interested in? I would need to clean up the code a bit before publishing to GitHub.

**Comment by soomro30** [comment]
I would like if you can share it with me. Thanks for your reply

**Comment by codezas** [comment]
I would like if you can share it with me. Thanks for the reply

**Comment by Rrivera5127** [comment]
email me at rrivera@esri.com and i will send you a zip of the prototype. Thanks!
